# PSM系统配置
psm:
  sys_iterations: 50
  exp_iterations: 5
  query_iterations: 3
  scan_iterations: 1
  debug: True
  draw_graph: False


# AI配置
ai:
  # api config
  openai_base: "https://api.whatai.cc/v1"
  openai_key: "sk-CUOVrhG13Dg2ynz8WxQSrvuBwJliZ3A3Y8OKzXAYRB62Zu3M"
  # NVIDIA API配置（使用Llama模型时需要）
  nvidia_key: ""
  # hyperparameters
  temperature: 0.5


# 测试配置
test:
  test_path: "../bench/data.jsonl"
  output_path: "result"
  save_history: True # 是否保存历史记录
  save_command: True # 是否保存命令
  # models: ['gpt35turbo', 'gpt4omini', 'gpt4o']
  models: ['gpt4omini']
  